In [1]:
import numpy as np
import pandas as pd

In [3]:
!gdown "https://drive.google.com/uc?id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_" -O ./data/mckinsey.csv

Using cookies from /Users/santhoshrishimarkonda/.cache/gdown/cookies.txt
Downloading...
From: https://drive.google.com/uc?id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_
To: /Users/santhoshrishimarkonda/Desktop/Code/CODINGWISE/Case Studies/Pandas/Mckinsey/data/mckinsey.csv
100%|██████████████████████████████████████| 83.8k/83.8k [00:00<00:00, 1.30MB/s]

In [4]:
data = pd.read_csv('./data/mckinsey.csv')
data.shape

(1704, 6)

In [5]:
data.head(10)

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106
5  Afghanistan  1977    14880372      Asia    38.438  786.113360
6  Afghanistan  1982    12881816      Asia    39.854  978.011439
7  Afghanistan  1987    13867957      Asia    40.822  852.395945
8  Afghanistan  1992    16317921      Asia    41.674  649.341395
9  Afghanistan  1997    22227415      Asia    41.763  635.341351

In [6]:
data.tail(10)

       country  year  population continent  life_exp     gdp_cap
1694  Zimbabwe  1962     4277736    Africa    52.358  527.272182
1695  Zimbabwe  1967     4995432    Africa    53.995  569.795071
1696  Zimbabwe  1972     5861135    Africa    55.635  799.362176
1697  Zimbabwe  1977     6642107    Africa    57.674  685.587682
1698  Zimbabwe  1982     7636524    Africa    60.363  788.855041
1699  Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [12]:
data.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [7]:
data[['life_exp','gdp_cap']]

      life_exp     gdp_cap
0       28.801  779.445314
1       30.332  820.853030
2       31.997  853.100710
3       34.020  836.197138
4       36.088  739.981106
...        ...         ...
1699    62.351  706.157306
1700    60.377  693.420786
1701    46.809  792.449960
1702    39.989  672.038623
1703    43.487  469.709298

[1704 rows x 2 columns]

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     1704 non-null   object
 1   year        1704 non-null   int64
 2   population  1704 non-null   int64
 3   continent   1704 non-null   object
 4   life_exp    1704 non-null   float64
 5   gdp_cap     1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB

In [9]:
data.describe()

             year    population     life_exp        gdp_cap
count  1704.00000  1.704000e+03  1704.000000    1704.000000
mean   1979.50000  2.960121e+07    59.474439    7215.327081
std      17.26533  1.061579e+08    12.917107    9857.454543
min    1952.00000  6.001100e+04    23.599000     241.165876
25%    1965.75000  2.793664e+06    48.198000    1202.060309
50%    1979.50000  7.023596e+06    60.712500    3531.846988
75%    1993.25000  1.958522e+07    70.845500    9325.462346
max    2007.00000  1.318683e+09    82.603000  113523.132900

In [10]:
data.describe(include=['object'])

            country continent
count          1704      1704
unique          142         5
top     Afghanistan    Africa
freq             12       624

### You have a list of columns and you want to seperate your numerical columns and categorical columns, how would you do that up

In [17]:
data[[col for col in data.columns if data[col].dtype != 'O']]

      year  population  life_exp     gdp_cap
0     1952     8425333    28.801  779.445314
1     1957     9240934    30.332  820.853030
2     1962    10267083    31.997  853.100710
3     1967    11537966    34.020  836.197138
4     1972    13079460    36.088  739.981106
...    ...         ...       ...         ...
1699  1987     9216418    62.351  706.157306
1700  1992    10704340    60.377  693.420786
1701  1997    11404948    46.809  792.449960
1702  2002    11926563    39.989  672.038623
1703  2007    12311143    43.487  469.709298

[1704 rows x 4 columns]

In [26]:
data[[col for col in data.columns if data[col].dtype != 'O']]

      year  population  life_exp     gdp_cap
0     1952     8425333    28.801  779.445314
1     1957     9240934    30.332  820.853030
2     1962    10267083    31.997  853.100710
3     1967    11537966    34.020  836.197138
4     1972    13079460    36.088  739.981106
...    ...         ...       ...         ...
1699  1987     9216418    62.351  706.157306
1700  1992    10704340    60.377  693.420786
1701  1997    11404948    46.809  792.449960
1702  2002    11926563    39.989  672.038623
1703  2007    12311143    43.487  469.709298

[1704 rows x 4 columns]

#### OR

In [23]:
data[[col for col in data.columns if type(data[col][0]) != str]]

      year  population  life_exp     gdp_cap
0     1952     8425333    28.801  779.445314
1     1957     9240934    30.332  820.853030
2     1962    10267083    31.997  853.100710
3     1967    11537966    34.020  836.197138
4     1972    13079460    36.088  739.981106
...    ...         ...       ...         ...
1699  1987     9216418    62.351  706.157306
1700  1992    10704340    60.377  693.420786
1701  1997    11404948    46.809  792.449960
1702  2002    11926563    39.989  672.038623
1703  2007    12311143    43.487  469.709298

[1704 rows x 4 columns]

In [18]:
data[[col for col in data.columns if data[col].dtype == 'O']]

          country continent
0     Afghanistan      Asia
1     Afghanistan      Asia
2     Afghanistan      Asia
3     Afghanistan      Asia
4     Afghanistan      Asia
...           ...       ...
1699     Zimbabwe    Africa
1700     Zimbabwe    Africa
1701     Zimbabwe    Africa
1702     Zimbabwe    Africa
1703     Zimbabwe    Africa

[1704 rows x 2 columns]

In [27]:
data[[col for col in data.columns if type(data[col][0]) == str]]

          country continent
0     Afghanistan      Asia
1     Afghanistan      Asia
2     Afghanistan      Asia
3     Afghanistan      Asia
4     Afghanistan      Asia
...           ...       ...
1699     Zimbabwe    Africa
1700     Zimbabwe    Africa
1701     Zimbabwe    Africa
1702     Zimbabwe    Africa
1703     Zimbabwe    Africa

[1704 rows x 2 columns]

In [32]:
data['country'].value_counts().sort_index()

country
Afghanistan           12
Albania               12
Algeria               12
Angola                12
Argentina             12
                      ..
Vietnam               12
West Bank and Gaza    12
Yemen, Rep.           12
Zambia                12
Zimbabwe              12
Name: count, Length: 142, dtype: int64

In [34]:
data.keys()

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [37]:
data.rename({"country": "Country", "year":"Year"}, axis=1, inplace=True)

In [38]:
data

          Country  Year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [39]:
data.drop('continent', axis=1)

          Country  Year  population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]