In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
netflix = pd.read_csv('/content/drive/MyDrive/Business Case PPT/Netflix Intro and Aerofit/netflix_titles.csv')
netflix.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [23]:
netflix['date_added'].dtype

dtype('O')

**Problem Statement**
Analyze the data and perform EDA to find intresting patterns and insights from the data. Write some useful recommendation to the netflix team.

- Challanges in the data
  - Get individual rows for cast, director and country which comes with values that are comma seperated.
  - Dealing with duration column
  - Extracting relevent date components from date_added column
  - Impute missing values using category wise imputation technique.

In [4]:
netflix.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [6]:
netflix[['title', 'director', 'cast', 'country']].head(20)

,title,director,cast,country
0,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States
1,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa
2,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN
3,Jailbirds New Orleans,NaN,NaN,NaN
4,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India
5,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN
6,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN
7,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin..."
8,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom
9,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States
10,"Vendetta: Truth, Lies and The Mafia",NaN,NaN,NaN
11,Bangkok Breaking,Kongkiat Komesiri,"Sukollawat Kanarot, Sushar Manaying, Pavarit M...",NaN
12,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic"
13,Confessions of an Invisible Girl,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",NaN
14,Crime Stories: India Detectives,NaN,NaN,NaN
15,Dear White People,NaN,"Logan Browning, Brandon P. Bell, DeRon Horton,...",United States
16,Europe's Most Dangerous Man: Otto Skorzeny in ...,"Pedro de Echave García, Pablo Azorín Williams",NaN,NaN
17,Falsa identidad,NaN,"Luis Ernesto Franco, Camila Sodi, Sergio Goyri...",Mexico
18,Intrusion,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh...",NaN
19,Jaguar,NaN,"Blanca Suárez, Iván Marcos, Óscar Casas, Adriá...",NaN

In [7]:
df = pd.read_csv('/content/drive/MyDrive/Business Case PPT/Netflix Intro and Aerofit/Demo.csv')
df.head()

                  title            dname type        date   duration
0              A bana B   Chintu, Mahesh    m  10/10/2023    190 min
1          Bus Itna Hi?       Lalu, Janu    m  11/10/2023    120 min
2             Sahi Baat            Sumit   tv  12/12/2023   1 season
3     Sumit Samhal Lega     Sumit, Rajat   tv  11/12/2022  2 seasons
4  Ruko Jara Sabar Karo  Hindustani Bahu    m  10/02/2022     60 min

In [11]:
a  = df['dname'].apply(lambda x:x.split(", ")).tolist()
a

[['Chintu', 'Mahesh'],
 ['Lalu', 'Janu'],
 ['Sumit'],
 ['Sumit', 'Rajat'],
 ['Hindustani Bahu']]

In [18]:
b = pd.DataFrame(a, index = df['title']).stack().reset_index().drop(columns = 'level_1').rename(columns = {0:'dname'})

In [19]:
b

                  title            dname
0              A bana B           Chintu
1              A bana B           Mahesh
2          Bus Itna Hi?             Lalu
3          Bus Itna Hi?             Janu
4             Sahi Baat            Sumit
5     Sumit Samhal Lega            Sumit
6     Sumit Samhal Lega            Rajat
7  Ruko Jara Sabar Karo  Hindustani Bahu

In [21]:
df['Movie_Mins'] = df[df['type']=='m']['duration'].apply(lambda x: int(x.split(" ")[0]))
df['Number of Seasons'] = df[df['type']=='tv']['duration'].apply(lambda x: int(x.split(" ")[0]))

In [22]:
df

,title,dname,type,date,duration,Movie_Mins,Number of Seasons
0,A bana B,"Chintu, Mahesh",m,10/10/2023,190 min,190.0,NaN
1,Bus Itna Hi?,"Lalu, Janu",m,11/10/2023,120 min,120.0,NaN
2,Sahi Baat,Sumit,tv,12/12/2023,1 season,NaN,1.0
3,Sumit Samhal Lega,"Sumit, Rajat",tv,11/12/2022,2 seasons,NaN,2.0
4,Ruko Jara Sabar Karo,Hindustani Bahu,m,10/02/2022,60 min,60.0,NaN

In [26]:
df['date']  = pd.to_datetime(df['date'])

In [27]:
df.dtypes

title                        object
dname                        object
type                         object
date                 datetime64[ns]
duration                     object
Movie_Mins                  float64
Number of Seasons           float64
dtype: object

In [28]:
df['date'].dt.year

0    2023
1    2023
2    2023
3    2022
4    2022
Name: date, dtype: int32

In [29]:
df['date'].dt.month

0    10
1    11
2    12
3    11
4    10
Name: date, dtype: int32

In [30]:
df['date'].dt.day

0    10
1    10
2    12
3    12
4     2
Name: date, dtype: int32

In [31]:
df['date'].dt.weekday

0    1
1    4
2    1
3    5
4    6
Name: date, dtype: int32

**EDA**

- Perfrom univariate and Bivariate analysis to find insights from the data.